import { inspectBackup } from '../src/backup.mjs';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { PlanStore } from '../src/plan-store.mjs';
import { sources } from '../src/discovery.mjs';
import { createApp } from '../src/server.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const store=new PlanStore(':memory:',()=>new Date('2026-09-11T12:00:00Z'));
const server=createApp(store);
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;
try {
  browser=await chromium.launch({headless:true,channel:'msedge'});
  const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'UTC'});
  const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];
  page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.getByText('Тут починається дослідження.',{exact:false}).waitFor();
  await page.getByLabel('Назва проєкту',{exact:true}).fill('Browser QA Ink');
  await page.getByLabel('Посилання на джерело').fill('https://example.com/qa');
  await page.getByLabel('Нотатки',{exact:true}).fill('<script>window.bad=true</script> Test fixture.');
  await page.getByRole('button',{name:'Додати проєкт ↗'}).click();
  let card=page.locator('#projects article').filter({hasText:'Browser QA Ink'});
  await card.getByRole('heading',{name:'Browser QA Ink'}).waitFor();
  assert.equal(await page.evaluate(()=>window.bad),undefined);
  page.once('dialog',dialog=>dialog.accept('Checked official evidence in QA'));
  await card.getByRole('button',{name:'Підтвердити перевірку джерела'}).click();
  await card.getByText('Джерело: перевірено вручну',{exact:true}).waitFor();
  await card.locator('summary').filter({hasText:'Умови кампанії та оцінка'}).click();
  await card.getByLabel('Тип кампанії',{exact:true}).selectOption('grant');
  await card.getByLabel('Статус за вашою перевіркою').selectOption('announced');
  await card.getByLabel('Умови участі / обмеження').fill('Live product required');
  await card.getByLabel('Доказ умов: цитата або висновок із джерела').fill('Example official grant rules reviewed');
  await card.getByLabel('Пояснення ризику / що ще не перевірено').fill('Reward allocation not guaranteed');
  await card.getByLabel('Ризик',{exact:true}).selectOption('medium');
  await card.getByLabel('Оцінка витрат, USD').fill('0');
  await card.getByRole('button',{name:'Зберегти оцінку',exact:true}).click();
  await card.getByText('Оголошено за перевіркою користувача',{exact:false}).waitFor();
  await card.getByLabel('Назва завдання',{exact:true}).fill('Check in fixture');
  await card.getByLabel('Тип завдання',{exact:true}).selectOption('check-in');
  await card.getByRole('button',{name:'＋ Завдання',exact:true}).click();
  let task=card.locator('.task').filter({hasText:'Check in fixture'});
  await task.locator('.schedule summary').click();
  await task.getByLabel('Дата й час',{exact:true}).fill('2026-09-10T12:00');
  await task.getByLabel('Повторення',{exact:true}).selectOption('daily');
  await task.getByRole('button',{name:'Зберегти розклад'}).click();
  await task.getByText('Настав час виконання',{exact:true}).waitFor();
  await page.locator('#agenda-content').getByText('Check in fixture',{exact:true}).waitFor();
  await page.locator('#agenda-content').getByRole('button',{name:'До завдання: Check in fixture',exact:true}).click();
  page.once('dialog',dialog=>dialog.accept('Checked in manually'));
  await task.getByRole('button',{name:'Записати виконання'}).click();
  await task.getByText('Термін протягом 24 годин',{exact:true}).waitFor();
  assert.equal(store.list()[0].tasks[0].completions.length,1);
  const imported=store.saveScan({source:sources[0],text:'Teams must have a live product. Grants require a builder application before the deadline.',hash:'browser-fixture',fetchedAt:new Date().toISOString()});
  store.verify(imported.projectId,{evidence:'Browser fixture evidence'});
  await page.reload();
  const importedCard=page.locator('#projects article').filter({hasText:'Ink Builder Program'});
  await importedCard.locator('summary').filter({hasText:'Знайти умови в матеріалах'}).click();
  await importedCard.getByRole('button',{name:'Додати вибране до завдань'}).click();
  await importedCard.locator('.task strong').filter({hasText:'Перевірити умови винагороди та спосіб відбору'}).waitFor();
  await page.reload();
  await page.locator('#projects article').first().waitFor();
  assert.equal(store.list().find(p=>p.name==='Browser QA Ink').assessment.data.estimatedCostUsd,0);
  await card.locator('summary').filter({hasText:'Умови кампанії та оцінка'}).click();
  await card.locator('summary').filter({hasText:'Фактичні винагороди та витрати'}).click();
  await card.getByLabel('Актив',{exact:true}).fill('USDC');
  await card.getByLabel('Кількість активу',{exact:true}).fill('5');
  await card.getByLabel('Оцінка на момент запису, USD',{exact:true}).fill('5.00');
  await card.getByLabel('Коли отримано / витрачено',{exact:true}).fill('2026-09-10T12:00');
  await card.getByLabel('Доказ результату: tx hash, посилання або опис',{exact:true}).fill('Browser fixture receipt');
  await card.getByRole('button',{name:'Записати результат',exact:true}).click();
  await card.locator('summary').filter({hasText:'Фактичні винагороди та витрати'}).click();
  await card.getByText('＋ 5 USDC',{exact:true}).waitFor();
  page.once('dialog',dialog=>dialog.accept('QA reversal'));
  await card.getByRole('button',{name:'Скасувати помилковий запис'}).click();
  await card.locator('summary').filter({hasText:'Фактичні винагороди та витрати'}).click();
  await card.getByText('Скасовано: QA reversal',{exact:true}).waitFor();
  await page.getByRole('searchbox').fill('Browser QA');
  await page.getByLabel('Статус проєкту Browser QA Ink',{exact:true}).selectOption('watching');
  await page.waitForFunction(()=>document.querySelector('#message').textContent==='Збережено.');
  await page.locator('#workflow-filter').selectOption('watching');
  await page.getByLabel('Статус проєкту Browser QA Ink',{exact:true}).waitFor();
  await page.getByRole('searchbox').fill('no-matching-project');
  await page.getByText('Показано 0 із 2',{exact:true}).waitFor();
  await page.getByRole('searchbox').fill('');
  await page.locator('#workflow-filter').selectOption('');
  mkdirSync('data/qa',{recursive:true});
  const downloading=page.waitForEvent('download');
  await page.getByRole('button',{name:'Завантажити копію даних',exact:true}).click();
  const download=await downloading;await download.saveAs('data/qa/download.sqlite');
  assert.equal(inspectBackup('data/qa/download.sqlite').projects,2);
  await page.getByRole('button',{name:'🤖 Помічник',exact:true}).click();
  await page.getByRole('button',{name:'Мої цікаві проєкти',exact:true}).click();
  await page.locator('#robot-panel').getByText(/Твої вибрані проєкти/).waitFor();
  await page.getByRole('button',{name:'Закрити',exact:true}).click();
  await page.screenshot({path:'data/qa/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'data/qa/mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile horizontal overflow');
  assert.deepEqual(errors,[]);
  console.log('Browser QA passed: create, verify, assessment, schedule, recurring completion, reload, mobile layout; no page errors.');
} finally {if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));store.close();}
